import type { Metadata } from 'next';
import './globals.css';
import ReactQueryClientProvider from './components/ReactQueryClientProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ReactQueryClientProvider>
  );
}
